name: CI

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FLASK_SECRET_KEY: development-secret-key
      FLASK_DEBUG: '1'
      ENABLE_WATCHERS: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pytest
        run: python -m pytest -q